name: Lighthouse CI
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * MON' # Run every Monday at midnight

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Lighthouse on multiple URLs
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ github.event.repository.homepage }}
            ${{ github.event.repository.homepage }}/blog
            ${{ github.event.repository.homepage }}/travel
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: '.github/lighthouse-config.json'

      - name: Save results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-results
          path: '.lighthouseci'
